version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: call_for_papers
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Leao2004
      POSTGRES_DB: callforpaperdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
