# Usa uma imagem base leve do OpenJDK 21
FROM eclipse-temurin:21-jdk

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o JAR gerado para o container
COPY target/*-runner.jar /app/app.jar

# Expondo a porta do Quarkus
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["java", "-jar", "/app/app.jar"]
